pod 'AFNetworking', '~> 3.0'
pod 'JSONModel', '~> 1.2'
pod 'FBSDKCoreKit'
pod 'FBSDKShareKit'
pod 'FBSDKLoginKit'
pod 'MWPhotoBrowser', '~> 2.1'
pod 'SWRevealViewController', '~> 2.3'
pod 'AsyncImageView', '~> 1.5'